Examples of pivot tables and crosstab in Pandas
-----------------------------------------------

# Make the element table

In [ ]:
import ase
import numpy as np
import pandas as pd

dtypes = np.dtype([('symbol', str), ('atomic mass', float)])
data = np.empty(0, dtype=dtypes)

elements = pd.DataFrame(data)
elements['symbol'] = ase.data.chemical_symbols
elements['atomic mass'] = ase.data.atomic_masses

# Molecule table

In [ ]:
df = pd.DataFrame(columns=['Molecule-ID', 'Atom symbol', 'x', 'y', 'z'])

from ase.build import molecule
i = 0

for mlc in ['H2O', 'NH3', 'CH4']:
    for atom in molecule(mlc):
        df.loc[i] = [mlc, atom.symbol, atom.x, atom.y, atom.z]
        i += 1
df

# Merge the tables

In [ ]:
mf = pd.merge(df, elements, how='inner', left_on='Atom symbol', right_on='symbol')
mf

# Cross tab approach 

suggested by @yhhuang at https://discord.com/channels/1009520272526807140/1066391376792670289/1070455241453080647.

We can query the result directly for molecules with 1 C and 3 or more H.

In [ ]:
ct = pd.crosstab(df['Molecule-ID'], df['Atom symbol'])
ct

In [ ]:
ct.query('C==1 & H>=3')

# Pivot table
An alternative approach is to get a Pivot Table. I find this confusing, and did not arrive at it without a lot of google help. This works on the merged dataframe. Basically, we group the Atom symbols by Molecule0ID, and count the number of each symbol to get the table. Then you can query that result.

There are *a lot* of variations of this that seem like they should work, but do not.

In [ ]:
pt = pd.pivot_table(mf, index='Molecule-ID', values='Atom symbol', columns='symbol',  aggfunc='count')
pt

In [ ]:
pt.query('C==1 & H>=3')